### ISSUE TITLE
Keyboard Shortcuts not working for Windows 10

### ISSUE THREAD

**Issue by Shujabutt** [eladnava/applicationize#130]
Keyboard shortcuts are not working for windows 10. I tried **Win+R**, **Ctrl+R** and **Alt+Ctrl+F** not working.
Test Website : Instagram

**Comment by eladnava** [comment]
Hi @Shujabutt,
Thanks for your report. This has been fixed in https://github.com/eladnava/applicationize/commit/2c6d4d6211eb009f5dbcfa81fd628dde3a337001. 

Please uninstall your existing Instagram extension and re-generate and re-install it from here:
https://applicationize.me/now

**Comment by Shujabutt** [comment]
Still not working I Downloaded crx from https://applicationize.me/now

**Comment by eladnava** [comment]
Hi @Shujabutt,
Apologies for that, please try generating the extension again, the new version wasn't fully deployed before.

**Comment by Shujabutt** [comment]
Thank you very much. Now it seems to be perfect. 🤩

**Comment by Shujabutt** [comment]
I have one question :
How to close Find dialogue?
I have to restart the app to close find dialogue box.

**Comment by eladnava** [comment]
Hi @Shujabutt,
The `Escape` key should close that dialog. :)

**Comment by Shujabutt** [comment]
Thanks very much. I really appreciate your work. ♥

**Comment by Shujabutt** [comment]
![Screenshot (152)](https://user-images.githubusercontent.com/65089197/124022477-478cc980-da06-11eb-8036-edfe2dc2f578.png)
I was trying to install the server on Windows 10 can you help?

**Comment by eladnava** [comment]
Hi @Shujabutt,
You're welcome! 

Seems like `npm` is unable to find the `git` executable. Please make sure it is in your PATH.

Please find `git.exe` in your system and add it to the PATH. More info:
https://stackoverflow.com/a/31167296/1123355
