### ISSUE TITLE
Window management (command + tab) is broken on Mac

### ISSUE THREAD

**Issue by eladnava** [eladnava/applicationize#17]
For some strange reason, it's impossible to Cmd + Tab from applicationized apps back to Chrome (nothing happens when selecting the Chrome icon).

**Comment by yannrouillard** [comment]
I have the same problem, but I am not sure it is related to Applicationize as I experienced the same issue with the Signal Desktop Client which is also packaged as an extension: https://chrome.google.com/webstore/detail/signal-private-messenger/bikioccmkafdpakkkcpdbppfkghcmihk

Currently you have to switch between windows of the same application (not between different applications) to see the chrome main window. You will notice that each applicationized web page still appears under the windows menu of the chrome browser.

**Comment by eladnava** [comment]
@yannrouillard That's correct, it's the case with any Chrome "packaged app" extension that runs in its own window.

**Comment by eladnava** [comment]
Chrome Version 53.0.2785.143 (64-bit) still suffers from this annoying bug which affects both hosted and packages apps, as well as bookmarked apps.

**Comment by guidokok** [comment]
I have the same issue. Version 54.0.2840.98 (64-bit)

**Comment by eladnava** [comment]
@sudhanshu16 Indeed looks like it's fixed now in the latest Chrome on macOS 🎉 

Give it a try:
https://applicationize.me/now

**Comment by sudhanshu16** [comment]
@eladnava I don't think that you understood me correctly. I meant that cmd+tab works when I "create a shortcut". App generated via applicationize still can't do this. If I do cmd+tab, the focus stays at the applicationized app and doesn't shift to main chrome window.

**Comment by eladnava** [comment]
My bad, I was using <kbd>CMD</kbd> + <kbd>`</kbd> (tilda) instead of <kbd>CMD</kbd> + <kbd>Tab</kbd>.

Yep, the issue still exists. Honestly I recommend using the built-in feature `Create a Shortcut` as it works really well 👍
