### ISSUE TITLE
Microsoft Teams Camera and Mic Access

### ISSUE THREAD

**Issue by vcolombo** [eladnava/applicationize#88]
Hi,

I'm trying to run the web version of Microsoft Teams through Applicationize and am running into problems with camera and mic access. I've chosen to allow access through the advanced settings when creating the app, but when I try to join a meeting Teams displays a notification stating I have to allow access by clicking on the icons that normally appear in the toolbar. Since Applicationize does not display this bar there are no icons for me to click on. Here is the message in Teams: "Give access to your camera and mic by clicking the camera icon as shown above, and then Always allow." There is an option to continue without granting this access, but doing that does not show any camera and mic devices accessible to teams.

Please let me know if I can provide any additional information. I'd love to get this working.

Thank you,

Vincent

**Comment by eladnava** [comment]
Hi @vcolombo,
I'd be glad to help investigate.

Can you please attach your `.crx` file generated from Applicationize which you are using to install the Microsoft Teams extension?

**Comment by vcolombo** [comment]
[teams.microsoft.com.crx.zip](https://github.com/eladnava/applicationize/files/3144498/teams.microsoft.com.crx.zip)

**Comment by eladnava** [comment]
@vcolombo I believe this issue was fixed in the newest version of Applicationize. We had a bug where selecting advanced options would sometimes not render them effective in the generated .crx file.

Please re-generate your extension here and reinstall it, then see if the microphone and mic access works:
http://applicationize.me/now

**Comment by vcolombo** [comment]
I regenerated the extension and am still seeing the same issue.

**Comment by eladnava** [comment]
Hi @vcolombo,
Please attach the new extension `.crx` for inspection.
